# Generated by Django 5.1 on 2024-08-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ordinal', models.IntegerField()),
            ],
        ),
    ]
