# Generated by Django 5.1 on 2024-08-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
