# Generated by Django 5.1 on 2024-08-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ordinal', models.IntegerField()),
            ],
        ),
    ]
